# Generated by Django 2.2.8 on 2020-06-02 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=20)),
                ('harga', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Barang')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateTimeField(auto_now=True)),
                ('tgl_pesan', models.DateTimeField()),
                ('pesan', models.BooleanField(default=False)),
                ('barangs', models.ManyToManyField(to='core.OrderBarang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
