# Generated by Django 2.2.8 on 2020-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200602_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
