# Generated by Django 2.2.8 on 2020-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_barang_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='slug',
            field=models.SlugField(),
        ),
    ]
