# Generated by Django 2.2.8 on 2020-06-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200602_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='hrg_diskon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
