# Generated by Django 2.2.8 on 2020-06-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_barang_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=1)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Barang')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pesan',
            new_name='dipesan',
        ),
        migrations.AlterField(
            model_name='order',
            name='barangs',
            field=models.ManyToManyField(to='core.BarangOrder'),
        ),
        migrations.DeleteModel(
            name='OrderBarang',
        ),
    ]
