# Generated by Django 2.2.8 on 2020-06-02 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200602_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangorder',
            name='dipesan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barangorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
