# Generated by Django 2.2.8 on 2020-06-28 01:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_barang_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bukti_invo',
            field=models.CharField(default=core.models.increment_invoice, editable=False, max_length=25),
        ),
    ]
