# Generated by Django 2.2.8 on 2020-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200628_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktibayar',
            name='foto',
            field=models.ImageField(upload_to='images/invoices'),
        ),
    ]
