# Generated by Django 2.2.8 on 2020-06-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200628_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktibayar',
            name='bukti_invo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
    ]
