# Generated by Django 2.2.8 on 2020-06-28 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200628_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bukti_invo',
            new_name='invoice',
        ),
        migrations.RemoveField(
            model_name='buktibayar',
            name='bukti_invo',
        ),
        migrations.AddField(
            model_name='buktibayar',
            name='invoice',
            field=models.CharField(default=django.utils.timezone.now, max_length=13),
            preserve_default=False,
        ),
    ]
