# Generated by Django 2.2.8 on 2020-06-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_buktibayar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktibayar',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
